dbt_demo:
  outputs:
    dev:
      account: Pdhkqps-ug61691
      database: RAW
      password: dbtPassword123
      role: transform
      schema: AIRBNB
      threads: 1
      type: snowflake
      user: dbt
      warehouse: compute_wh

    UAT:
      account: Pdhkqps-ug61691
      database: UAT
      password: dbtPassword123
      role: transform
      schema: AIRBNB
      threads: 1
      type: snowflake
      user: dbt
      warehouse: compute_wh

  target: dev

