select 
    r.LISTING_ID, REVIEW_DATE, REVIEWER_NAME, REVIEW_TEXT, REVIEW_SENTIMENT,
    LISTING_NAME, ROOM_TYPE, MINIMUM_NIGHTS, PRICE, HOST_ID, HOST_NAME, HOST_IS_SUPERHOST
from
STG.AIRBNB.FACT_REVIEWS r left join 
INT.AIRBNB.DIM_LISTINGS_W_HOSTS lh on r.listing_id = lh.listing_id